version: '3.7'

services:
  nrpe-demo:
    image: nrpe-demo
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - maria-db
#  maria-db:
#    image: mariadb:10.4
#    environment:
#      - MYSQL_ROOT_PASSWORD=changeit
#    ports:
#      - 5432:5432
